Repository wasp-os/wasp-os, pull requests merged in 2023-08, with the labels that each got.

#440 Update draw565.py
  wasp/draw565.py
Labels: documentation

#441 Add 15 Puzzle app
  README.rst
  apps/puzzle15.py
  docs/apps.rst
  res/icons/puzzle_15_icon.png
  res/screenshots/Puzzle15App.png
Labels: new app

#432 wasp: Allow for clearing a tick request
  wasp/wasp.py
Labels: enhancement
